import Head from "next/head";
import RootLayout from "@/components/common/layout/RootLayout";
import DesignStudioHero from "@/components/hero/DesignStudioHero";
import DesignStudioAbout from "@/components/about/DesignStudioAbout";
import DigitalMarketingWorkflow from "@/components/workflow/DigitalMarketingWorkflow";
import DigitalAgencyService from "@/components/service/DigitalAgencyService";
import DesignStudioProtfolio from "@/components/portfolio/DesignStudioProtfolio";
import DesignStudioBlog from "@/components/blog/DesignStudioBlog";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RootLayout header="header2" footer="footer3">
          <DesignStudioHero />
          <DesignStudioAbout />
          <DigitalMarketingWorkflow />
          <DigitalAgencyService />
          <DesignStudioProtfolio />
          <DesignStudioBlog />
        </RootLayout>
      </main>
    </>
  );
}
